spring.application.name=StreamDSL
topic.mainData=mainTopic
topic.additionalData=additionalTopic
topic.output=output
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.schema-registry=http://localhost:9091
