spring.application.name=ProcessorAPI
topic.mainData=mainTopic
topic.additionalData=additionalTopic
topic.output=output
spring.kafka.bootstrap-servers=localhost:9090
spring.kafka.schema-registry=localhost:9091
